# Generated by Django 3.2.3 on 2021-06-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default='2012-09-04 06:00:00.000000-08:00'),
            preserve_default=False,
        ),
    ]
